#!/bin/sh
stty -F /dev/ttyUSB0 9600

cd /home/pi/kWh
while true; do
 awk '{ print $0 > "/dev/stderr"; if (/^Cycle/) { print "update kWh.rrd N:" $5; fflush(); } }' < /dev/ttyUSB0 | rrdtool -
 sleep 1
done
